### ISSUE TITLE
How to query for a single component given an entity?

### ISSUE THREAD

**Issue by RUSshy** [roig/destral_ecs#2]
Hello

Inside a view, i want to check if an entity has a specific component, and if he does query it

I could create a single view and then check for the entity id, but that seems overkill when i just want to check if it has a flag and query its value

Thanks!

**Comment by roig** [comment]
Hello, you can use:
```
/*
    Returns the pointer to the given component type data for the entity
    or nullptr if the entity doesn't have this component.
    Warning: Using an invalid entity results in undefined behavior.
    Note: This is safer but slower than de_get.
*/
void* de_try_get(de_ecs* r, de_entity e, de_cp_type cp_type);
```

Views are for iteration, if you just want to check for a specific component in a specific entity just use that function.

**Comment by RUSshy** [comment]
Awesome thanks a lot!
