### ISSUE TITLE
Incorrect number of entities if de_emplace got called before

### ISSUE THREAD

**Issue by RUSshy** [roig/destral_ecs#4]
Let's say:

- create 100 entities with component X
- add component Y yo each entity with component X
- iterate over entities with component Y
- i should get 100 entities
- problem: iterating over the views only give me 50 entities

I'm not sure if i explain the problem correctly, so i managed to get a sample that reproduces the bug

```
λ "c:\LLVM\bin\clang.exe" main.c && .\a.exe
added: 100
removed: 50
Assertion failed: removed == SIZE, file main.c, line 953
```
```C
typedef struct ccube {
} ccube;
typedef struct cremove {
} cremove;

static const de_cp_type ccube_type = DE_MAKE_CP_TYPE(1, ccube);
static const de_cp_type cremove_type = DE_MAKE_CP_TYPE(2, cremove);

int main()
{
    de_ecs* r = de_ecs_make();

    const int SIZE = 100;

    // create cubes
    for(int i = 0; i < SIZE; i++)
    {
        de_entity e1 = de_create(r);
        ccube* v1 = de_emplace(r, e1, ccube_type);
    }

    // add remove component
    int added = 0;
    for (de_view v = de_create_view(r, 1, (de_cp_type[1]) {ccube_type }); de_view_valid(&v); de_view_next(&v))
    {
        de_entity e = de_view_entity(&v);
        de_emplace(r, e, cremove_type);
        added++;
    }
    printf("added: %i\n", added);
    assert(added == SIZE);

    int removed = 0;
    // remove entities with cremove
    for (de_view v = de_create_view(r, 1, (de_cp_type[1]) {cremove_type}); de_view_valid(&v); de_view_next(&v))
    {
        de_entity e = de_view_entity(&v);
        de_destroy(r, e);
        removed++;
     }

    printf("removed: %i\n", removed);
    assert(removed == SIZE);

    return 0;
}
```

**Comment by roig** [comment]
I'm sorry but this is a limitation of the system. You can't delete/add entities while iterating.

**Comment by RUSshy** [comment]
Oh i see!

What is the recommended way to delete entities that has a specific component?
And for spawning particle effect entity when an enemy got hit?

**Comment by roig** [comment]
Maybe you can make a helper function that iterates all the entities you want to destroy and save them in a de_entity array. Then after the iteration just iterate that array of de_entitys and call de_destroy(..).

I just want to warn you that the library is not battletested :( and now I don't have too much time to support it and maybe it has bugs.
